image: python:latest  # On utilise une image avec Python, n√©cessaire pour MkDocs

pages:
  stage: deploy
  script:
    - pip install mkdocs
    - pip install mkdocs-nav-weight
    - mkdocs build --verbose --site-dir public  # Construit le site dans le dossier "public"
  artifacts:
    paths:
      - public
  only:
    - main
    - master